name: Download Realtor Metro Data (Twice Daily)

on:
  schedule:
    # Morning run: 10:00 UTC (5AM EST / 6AM EDT)
    - cron: '0 10 1-7 * *'
    # Midday run: 18:00 UTC (1PM EST / 2PM EDT)
    - cron: '0 18 1-7 * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run download script
        run: python download_realtor_metro_data.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/realtor_metro_data.csv
          git commit -m "Update Realtor metro data"
          git push
